# Generated by Django 2.2.2 on 2019-06-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=254)),
                ('user_location', models.CharField(max_length=30)),
                ('registered_on', models.DateTimeField(verbose_name='registered on')),
            ],
        ),
    ]
